[project]
    authors = [
        { name = "Michael C. Burkhart", email = "burkh4rt@uchicago.edu" },
        { name = "Luke Solo", email = "lsolo@uchicago.edu" },
        { name = "Inhyeok Lee", email = "ihlee@uchicago.edu" },
        { name = "S'Khaja Charles", email = "skhaja@uchicago.edu" },
        { name = "Brett K. Beaulieu-Jones", email = "beaulieujones@uchicago.edu" },
    ]
    classifiers = [
        "Development Status :: 2 - Pre-Alpha",
        "Intended Audience :: Science/Research",
        "Natural Language :: English",
        "Programming Language :: Python :: 3",
    ]
    dependencies = [
        "accelerate==0.34.2",
        "click<8.2",
        "clifpy==2.1.0",
        "cocoa-tokenizer==26.9.1",
        "cotorra==26.9.0",
        "flwr[simulation]==1.18.0",
        "huggingface_hub>=0.23.2,<1.0",
        "kaleido",
        "plotly",
        "protobuf==4.25.3",
        "ray==2.31.0",
        "rich",
        "scikit-learn",
        "torch",
        "transformers==4.45.2",
        "typer==0.12.5",
    ]
    description = "choreographed federated learning of generative event models"
    keywords = [
        "federated learning",
        "generative event models",
        "configurable training",
    ]
    license = "MIT"
    license-files = [ "LICEN[CS]E.*" ]
    name = "coreopsis"
    readme = { file = "README.md", content-type = "text/markdown" }
    requires-python = ">=3.11"
    version = "26.6.0"

    [project.scripts]
        coreopsis = "coreopsis.cli:main"

    [project.urls]
        Repository = "https://github.com/bbj-lab/coreopsis"

    [project.optional-dependencies]
        dev = [ "pip", "ruff" ]

[build-system]
    build-backend = "setuptools.build_meta"
    requires      = [ "setuptools", "wheel" ]

[tool.flwr.app]
    publisher = "burkh4rt"

    [tool.flwr.app.components]
        clientapp = "coreopsis.client_app:app"
        serverapp = "coreopsis.server_app:app"

    [tool.flwr.app.config]
        datasets = '''
        [
            "mimic-icu-3.0.0", "ucmc-icu-3.0.0", "nu_cdh-icu-3.0.0", "nu_dh-icu-3.0.0",
            "nu_hh-icu-3.0.0", "nu_kh-icu-3.0.0", "nu_lfh-icu-3.0.0",
            "nu_mh-icu-3.0.0", "nu_nmh-icu-3.0.0", "nu_ph-icu-3.0.0", "rush-icu-3.0.0",
            "eicu-73-icu-3.0.0", "eicu-122-icu-3.0.0", "eicu-148-icu-3.0.0",
            "eicu-165-icu-3.0.0", "eicu-167-icu-3.0.0", "eicu-176-icu-3.0.0",
            "eicu-183-icu-3.0.0", "eicu-188-icu-3.0.0", "eicu-199-icu-3.0.0",
            "eicu-208-icu-3.0.0", "eicu-243-icu-3.0.0", "eicu-248-icu-3.0.0",
            "eicu-252-icu-3.0.0", "eicu-264-icu-3.0.0", "eicu-281-icu-3.0.0",
            "eicu-283-icu-3.0.0", "eicu-300-icu-3.0.0", "eicu-307-icu-3.0.0",
            "eicu-331-icu-3.0.0", "eicu-338-icu-3.0.0", "eicu-345-icu-3.0.0",
            "eicu-365-icu-3.0.0", "eicu-394-icu-3.0.0", "eicu-411-icu-3.0.0",
            "eicu-413-icu-3.0.0", "eicu-416-icu-3.0.0", "eicu-417-icu-3.0.0",
            "eicu-420-icu-3.0.0", "eicu-443-icu-3.0.0", "eicu-449-icu-3.0.0",
            "eicu-458-icu-3.0.0"
        ]
        '''
        fed-strategy = "FedAvg" # options: FedAvg, FedAvgM, FedAdam
        num-server-rounds = 10
        output-home = "output"
        processed-data-dir = "processed"
        training-config = "src/coreopsis/config/training.yaml"

[tool.flwr.federations]
    default = "standard"

    [tool.flwr.federations.local]
        options.backend.client-resources.num-cpus = 0.3
        options.backend.client-resources.num-gpus = 0
        options.num-supernodes                    = 42

    [tool.flwr.federations.minimal]
        options.backend.client-resources.num-cpus = 1
        options.backend.client-resources.num-gpus = 1
        options.num-supernodes                    = 42

    [tool.flwr.federations.standard]
        options.backend.client-resources.num-cpus = 1
        options.backend.client-resources.num-gpus = 1
        options.num-supernodes                    = 42

[tool.ruff]
    extend-exclude = [ "*.md" ]
    line-length    = 88

    [tool.ruff.format]
        docstring-code-format     = true
        indent-style              = "space"
        line-ending               = "lf"
        quote-style               = "double"
        skip-magic-trailing-comma = true

    [tool.ruff.lint]
        ignore = [ "E731" ]
        select = [ "E", "F", "I" ]

        [tool.ruff.lint.isort]
            known-first-party       = [ "cocoa", "cotorra", "coreopsis" ]
            split-on-trailing-comma = false

[tool.setuptools]
    include-package-data = true

    [tool.setuptools.packages.find]
        where = [ "src" ]

    [tool.setuptools.package-data]
        "coreopsis.config" = [ "*.yaml" ]
